Organizations:
    - &Korea
        Name: KoreaMSP
        ID: KoreaMSP
        MSPDir: crypto-config/peerOrganizations/korea.example.com/msp
        AnchorPeers:
            - Host: peer0.korea.example.com
              Port: 7051

    - &USA
        Name: USAMSP
        ID: USAMSP
        MSPDir: crypto-config/peerOrganizations/usa.example.com/msp
        AnchorPeers:
            - Host: peer0.usa.example.com
              Port: 7051

    - &Mexico
        Name: MexicoMSP
        ID: MexicoMSP
        MSPDir: crypto-config/peerOrganizations/mexico.example.com/msp
        AnchorPeers:
            - Host: peer0.mexico.example.com
              Port: 7051

    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/example.com/msp

Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true

    Orderer: &OrdererCapabilities
        V2_0: true

    Application: &ApplicationCapabilities
        V2_0: true

Application: &ApplicationDefaults
    ACLs: &ACLs
    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: etcdraft
    Addresses:
        - orderer.example.com:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Capabilities:
        <<: *OrdererCapabilities
    Organizations:

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities
    Orderer: &OrdererDefaults
    Application: &ApplicationDefaults

Profiles:
    OrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Korea
                    - *USA
                    - *Mexico

    ChannelConfig:
        <<: *ChannelDefaults
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Korea
                - *USA
                - *Mexico

